
name: SonarCloud analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Convert Jupyter Notebooks to Python
        run: |
          pip install nbconvert
          find . -name "*.ipynb" -exec jupyter nbconvert --to script {} \;

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan
        run: |
          sonar-scanner 
            -Dsonar.organization=lok-jagruti-kendra-university 
            -Dsonar.projectKey=Lok-Jagruti-Kendra-University_101 
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.token=${ secrets.SONAR_TOKEN } 
            -Dsonar.python.version=3.8 
            -Dsonar.java.binaries=target/classes 
            -Dsonar.inclusions=**/*.java,**/*.py,**/*.ipynb  
            -Dsonar.sources=.

      - name: Analyze with SonarCloud

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@v2.2.0
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${ secrets.SONAR_TOKEN }   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=Lok-Jagruti-Kendra-University_101
            -Dsonar.organization=lok-jagruti-kendra-university            
            -Dsonar.token=44008bdc256019db2fd5c2fc7693fb2a319dc611
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false
          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
          projectBaseDir: .
        